### ISSUE TITLE
[Question] Benefits of CodeIgniter Security vs HTML Purifier?

### ISSUE THREAD

**Issue by hackel** [GrahamCampbell/Laravel-Binput#18]
I was wondering what the benefits are, if any, of using the CodeIgniter Security class instead of the single-purpose [HTML Purifier](htmlpurifier.org) library.  I don't actually have any preference for one or the other, just curious about your reasoning.

I really like Binput's approach of wrapping Illuminate\Http\Request for transparent input sanitization.  It seems like this could even be used with FormRequest as well (clean before validation), no?

It looks like an HTML Purifier-based library like [etcinit/purifier](https://github.com/etcinit/purifier) could function as a drop-in replacement for Laravel-Security, since they both implement a simple clean() method.

**Comment by GrahamCampbell** [comment]
Html purifier doesn't support html5.

**Comment by GrahamCampbell** [comment]
You can still use my security package directly in form requests.
