### ISSUE TITLE
Allow keys to be null as in Laravel's Request class

### ISSUE THREAD

**Issue by passioncoder** [GrahamCampbell/Laravel-Binput#19]
Laravel's Request class allowes the `$key` parameter to be `null` for the methods `old` and `input`, which is not the case in your Binput class. E.g. `Input::old()` returns an array with all input parameters.

Please adapt this behaviour or at least mention this difference in the documentation. Currently the doc says "The [...] methods have an identical api to the methods found on the laravel request class ...", which is not exactly true.

**Comment by GrahamCampbell** [comment]
Yeh, I don't like laravel's behaviour. I think you should be manually asking for they keys you want.
