### ISSUE TITLE
Call to undefined method GrahamCampbell\Binput\Facades\Binput::get()

### ISSUE THREAD

**Issue by pixelgremlins** [GrahamCampbell/Laravel-Binput#20]
Error: 
FatalErrorException in Facade.php line 210: Call to undefined method GrahamCampbell\Binput\Facades\Binput::get()
CODE:
Route::get('test', function(){
        $test = BInput::get('test');
	return $test;
});
test: 
http://localhost/test?test=hello

**Comment by lagbox** [comment]
Service Provider isn't registered.

**Comment by GrahamCampbell** [comment]
Also, `Binput` needs a lower case I. If you use the incorrect case, you may experience issues with autoloading on systems with case sensitive filesystems.
