### ISSUE TITLE
input() bug

### ISSUE THREAD

**Issue by olsgreen** [GrahamCampbell/Laravel-Binput#24]
To maintain 'identical api' with the laravel request class the package should support calling `input()` with no parameters. Currently it errors out due to lack of a parameter.

**Comment by GrahamCampbell** [comment]
The docs need updating then. I intentionally didn't include this.

**Comment by oytuntez** [comment]
I think we should aim at extending the core Input functionality. What do you think @GrahamCampbell? I like drop-in replacements, so much better than applying Binput all over the place.

I am using Binput in Input alias at the moment, but some features are missing from the Input facade, such as `has()`.

**Comment by GrahamCampbell** [comment]
> I am using Binput in Input alias at the moment, but some features are missing from the Input facade, such as has().

I'd be open to a PR to add that. :)

**Comment by GrahamCampbell** [comment]
I am not aware of anything else missing, other than any intentional changes I've made to avoid the multitude of ways of calling methods, which I don't like, and any missing methods from the actual facade, which I have not yet checked myself to confirm.
