### ISSUE TITLE
Binput ignore validation rules

### ISSUE THREAD

**Issue by ssuhat** [GrahamCampbell/Laravel-Binput#26]
Hi,

I've tried to extend the Binput directly to my request, but it ignore all the validation rules.

    //Request.php
     use GrahamCampbell\Binput\Binput;
     abstract class Request extends Binput
     {
   
      }

     //UserRequest
      public function rules()
       {
         return [
            'email'             => 'required|email|unique:users,email',
            'password'          => 'required|numeric|digits:6',
        ];
      }

It works perfectly. Everything is clean and trim. But if I try to not fill the email field. But it pass the validation request. 

Am I doing mistake or is this how binput works?
Thanks

**Comment by GrahamCampbell** [comment]
Binput is nothing to do with form requests.
