### ISSUE TITLE
No stable v11.x version is available via Composer

### ISSUE THREAD

**Issue by imgrant** [GrahamCampbell/Laravel-Binput#37]
Hello,

When upgrading a Laravel application to v10.x of the Laravel framework, I get the following error message from Composer:
```
composer.json requires graham-campbell/binput ^11.0, found graham-campbell/binput[11.0.x-dev] but it does not match your minimum-stability.
```

Browsing https://packagist.org/packages/graham-campbell/binput, it looks like `v11.0` is not available there (only `11.0.x-dev`). I'd prefer not to drop my `minimum-stability` (to install `11.0.x-dev`), is a `v11.0` published release in the works? 🙏

**Comment by GrahamCampbell** [comment]
v11.0.0 has now been tagged, and includes PHP 8.3 support, too.
